### ISSUE TITLE
[0.9] [h] Нет УТП на основе анализа конкурентов, потребителей и наших возможностей/потенциала

### ISSUE THREAD

**Issue by akaSun4e** [healthUapp/Dozens-hUa#18]
![rebuildArtboard 8-1.png](https://user-images.githubusercontent.com/96766476/178347809-51501d27-c5bd-4be7-a4ea-3f55273b3c76.png)

**Comment by YuliyaSilvan** [comment]
УТП на сайте:
1. для бизнеса - "Increase employee productivity. Reduce company costs"
2. для пользователей - "Ergonomic activity breaks for your long-term well-being"
