### ISSUE TITLE
[0.0] [h] Нет презентации продукта (пдф) - есть

### ISSUE THREAD

**Issue by akaSun4e** [healthUapp/Dozens-hUa#43]

**Comment by akaSun4e** [comment]
[версия лайт сделанная для Польши](https://docs.google.com/presentation/d/1l0Hfqe-0-OndOfDFK4S3AsnzwH58ADZg2jFz0OdARec/edit?usp=sharing)
[на данный момент незаконченная версия для инвесторов ](https://docs.google.com/presentation/d/1gmMywAar4BwVDQWz2X__L0PNQGN5BJFY0-fzUcAuxhE/edit?usp=sharing)

**Comment by YuliyaSilvan** [comment]
после доработки продукта (сама платформа, сайт, кабинет, онбординг, внедрение и тд) будет создана новая полноценная красивая презентация (беру на себя)
